# Docs: https://taskfile.dev/#/usage
version: "3"

tasks:
  lint:
    cmds:
      - golangci-lint run

  format:
    cmds:
      - go fmt ./...

  build:
    cmds:
      - go build -v -o ./bin/ .

  run:
    cmds:
      - go run .
