name: Build and Push

on:
  # Manual Invocation
  workflow_dispatch:
    inputs:
      ref:
        description: Branch, tag or commit hash
        type: string
        default: main
      tags:
        description: Docker Image Tag(s)
        type: string
        default: develop

  # Invocation from workflow
  workflow_call:
    inputs:
      ref:
        description: Branch, tag or commit hash
        type: string
        default: main
      tags:
        description: Docker Image Tag(s)
        type: string
        required: true

env:
  IMAGE_REPOSITORY: arranhs/gorker

jobs:
  build-push:
    name: Build and Push
    runs-on: ubuntu-latest
    timeout-minutes: 20
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Setup qemu
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: arranhs
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get image tags
        id: get-image-tags
        run: |
          IMAGE_TAGS=$(echo "$IMAGE_TAGS" | tr ',' '\n')

          FULL_TAGS=""
          while read -r IMAGE_TAG; do
            FULL_TAGS+="$IMAGE_REPOSITORY:$IMAGE_TAG\n"
          done <<<"$IMAGE_TAGS"

          {
            echo "tags<<EOF"
            echo -e "$FULL_TAGS"
            echo "EOF"
          } >>"$GITHUB_OUTPUT"

          echo -e "
          Tags:
          $FULL_TAGS
          "
        env:
          IMAGE_TAGS: ${{ inputs.tags }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.get-image-tags.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
